import mongoose ,{Schema} from "mongoose";
const listschema=new Schema(
    {
        Date:
        {
            type:Number,
            required:true
        }
        ,Month:
        {
            type:String,
            required:true
        }
        ,Year:
        {
            type:Number,
            required:true
        },PrizeBondAmount:
        {
            type:Number,
            require:true
        },FirstWin:
        {
            type:[String],
            require:true
        },FirstPrize:
        {
            type:Number,
            require:true
        },SecondWin:
        {
            type:[String],
            require:true
        },SecondPrize:
        {
            type:Number,
            require:true
        },ThirdWin:
        {
            type:[String],
            require:true
        },ThirdPrize:
        {
            type:Number,
            require:true
        }
        
    },{
       timestamps:true
    }
)
export const List =mongoose.model("List", listschema);